[package]
name = "restexample"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = "0.4"
log = "0.4"
pretty_env_logger = "0.5.0"
serde = { version = "1", features = ["derive"] }
taos = "*"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
